/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "Stm32_F103C6_gpio_driver.h"
#include "Stm32_F103X6.h"
#include "KEYPAD_Config.h"
#include "KEYPAD_interface.h"
#include "LCD_Config.h"
#include "LCD_interface.h"


void clock_init()
{
	// Enable IO port A clock
	RCC_GPIOA_CLK_EN();
	// Enable IO Port B clock
	RCC_GPIOB_CLK_EN();
}
/*Calculator Variables */
uint32 number =0;
double result =0;
uint8 operation =0 ;

/*Calculator APIS */
void DO_Operation(uint8 opp);

int main()
{
	clock_init();
	LCD_init();
	KEYPAD_init();
	uint8 pressed_key ;

	while(1)
	{
		pressed_key=KEYPAD_GetKey();
		if (pressed_key != 0)
		{
			LCD_Send_Character(pressed_key);
			if(pressed_key == '/' || pressed_key == '*' || pressed_key == '-' || pressed_key == '+')
			{
				if (operation == 0 )
				{
				result = number ;
				operation = pressed_key ;
				number =0 ;
				}
				else
				{
					DO_Operation(operation);
					operation = pressed_key ;
					number = 0;
				}
			}
			else if (pressed_key == '=')
			{
				DO_Operation(operation);
				LCD_Clear_Screen();
				LCD_Display_Real_Number(result);
				result =0 ;
				number =0 ;
				operation =0 ;
			}
			else if(pressed_key == 'C')
			{
				result =0 ;
				number =0 ;
				LCD_Clear_Screen();
			}
			else
			{
				number = (number*10)+ (pressed_key - '0');
			}

		}


	}
}
void DO_Operation(uint8 opp)
{
	switch(opp)
	{
	case '/' :
		result /= number ;
		break ;
	case '*':
		result *= number ;
		break;
	case '-' :
		result -= number ;
		break ;
	case '+' :
		result += number ;
		break;
	}

}
