/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

typedef volatile unsigned int vuint32_t ;
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
// register address
#define GPIOA_BASE 0x40010800
#define GPIOA_CRH *(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_ODR *(volatile uint32_t *)(GPIOA_BASE + 0x0C)

// AFIO
#define AFIO_BASE 0x40010000
#define AFIO_EXTICR1  *(volatile uint32_t *)(AFIO_BASE + 0x08)

#define RCC_BASE    0x40021000
#define RCC_APB2ENR  *(volatile uint32_t *)(GPIOA_BASE + 0x18)

// EXTI registers
#define EXTI_BASE    0x40010400
#define EXTI_IMR  *(volatile uint32_t *)(EXTI_BASE + 0x00)
#define EXTI_RTSR  *(volatile uint32_t *)(EXTI_BASE + 0x08)
#define EXTI_PR  *(volatile uint32_t *)(EXTI_BASE + 0x14)

// NVIC control register
#define NVIC_ISER0  *(volatile uint32_t *)(0xE000E100)

void clock_init()
{
	// Enable IO port A clock
	RCC_APB2ENR |= (1<<2) ;
	// Enable AFIO clock
	RCC_APB2ENR |= (1<<0) ;
}
void GPIO_init()
{
	//Enable pin13 PortA as output
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0x00200000;
}
int main(void)
{
	clock_init();
	GPIO_init();

	// select PA0 as interrupt input for EXTI0 (0000: PA[x] pin )
	AFIO_EXTICR1 |= 0x00 ;

	//Enable raising Edge trigger for EXTI0
	EXTI_RTSR |= (1<<0);

	//Enable Mask EXTI0
	EXTI_IMR |= (1<<0);

	// Enable NVIC IRQ 6 (EXTI0)
	NVIC_ISER0 |= (1<<6);


	/* Loop forever */
	while(1);
}

void EXTI0_IRQHandler(void)
{
	//toggle led
	GPIOA_ODR ^= (1<<13);

	// clear the EXTI1 pending Request
	EXTI_PR |= (1<<0);
}

